#!/bin/bash
#SBATCH -o splicing.%j.out
#SBATCH -e splicing.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=$USER@jax.org
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 1-01:00:00
 
 
cd $SLURM_SUBMIT_DIR
date;hostname;pwd

module load singularity
curl -fsSL get.nextflow.io | bash

./nextflow run main.nf \
	-config conf/examples/human_test.config  -profile base,sumner -resume -with-report human_test.html -with-timeline human_test_timeline.html human_test.png
