#!/bin/bash
#SBATCH -o splicing.%j.out
#SBATCH -e splicing.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=$USER@jax.org
#SBATCH --mem=20000
#SBATCH --cpus-per-task=4
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 1-01:00:00


cd $SLURM_SUBMIT_DIR
date;hostname;pwd

module load singularity

curl -fsSL get.nextflow.io | bash

#./nextflow run /projects/anczukow-lab/splicing_pipeline/splicing-pipelines-nf/main.nf \
#	--outdir ${SLURM_SUBMIT_DIR} \
#	-config NF_splicing_pipeline.config \
#	-profile base,sumner --max_memory 200.GB --max_cpus 30 -resume
./nextflow run main.nf               \
	--outdir ${SLURM_SUBMIT_DIR} \
	-config conf/examples/MYC_MCF10A_0h_vs_MYC_MCF10A_8h.config \
	-profile base,sumner \
        --max_memory 200.GB \
        --max_cpus 30 \
        -resume \
        -with-report phil_update_MYC_2020Jul6_800_report.html \
        -with-trace phil_update_MYC_2020Jul6_800_trace.txt \
        -with-timeline phil_update_MYC_2020Jul6_800_timeline.html \
        -with-dag phil_update_MYC_2020Jul6_800_DAG.png
